language: ruby
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without dev
rvm:
  - 2.1.9
  - 2.2.5
  - jruby-9.1.2.0
  - rbx-2.4.1
  - rbx-2.5.8
matrix:
  allow_failures:
    # rbx no longer builds on travis
    - rvm: rbx-2.4.1
    - rvm: rbx-2.5.8
  fast_finish: true
